---
title: "Lab 6: MATH 4753"
author: "Hunter DeVoe"
date: "February 8, 2023"
output: 
  html_document:
    toc: yes
    toc_float: yes
    theme: spacelab
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(pacman, tidyverse, lattice, s20x, knitr, devtools, roxygen2, testthat)
```

# Task 1

```{r}
getwd()
```

# Task 2

## Use layout() to construct a plotting region that will take 4 plots. Use it to plot 4 normal curves with the following parameters.  

* $\mu = 10, \sigma = 4$  

* $\mu = 10, \sigma = 2$  

* $\mu = 5, \sigma = 10$  

* $\mu = 5, \sigma = \frac{1}{2}$

```{r}
layout(matrix(1:4, nr=2,nc=2))

curve(dnorm(x, mean=10,sd=4),xlim=c(-10,30))

curve(dnorm(x, mean=10,sd=2),xlim=c(-10,30))

curve(dnorm(x, mean=5,sd=10),xlim=c(-40,40))

curve(dnorm(x, mean=5,sd=1/2),xlim=c(0,10))
```

## Plot the following regions and probabilities using one graphical interface per plot (use 4 dec. places)  

* $Y ~ N(0, 1), P(Y \geq 2)$  

* $Y ~ N(\mu = 4, \sigma = 2), P(1 \leq Y \leq 5)$  

* $Y ~ N(\mu = 10, \sigma = 4), P(Y < 10)$  

* $Y~N(\mu = -2, \sigma = \frac{1}{2}), P(-3 < Y \leq -2)$





















```{r}
# CLEAN UP #################################################

# Clear environment
rm(list = ls()) 

# Clear packages
p_unload(all)  # Remove all add-ons

# Clear plots
dev.off()  # But only if there IS a plot

# Clear console
cat("\014")  # ctrl+L

# Clear mind :)
```
